# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fib.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "micro_rb.fib_pb.Request" do
    optional :n, :int32, 1
  end
  add_message "micro_rb.fib_pb.Response" do
    optional :n, :int32, 1
  end
end

module MicroRb
  module FibPb
    Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_rb.fib_pb.Request").msgclass
    Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_rb.fib_pb.Response").msgclass
  end
end
