# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'micro_rb.debug.Request' do
  end
  add_message 'micro_rb.debug.Response' do
    optional :status, :string, 1
  end
end

module MicroRb
  module Debug
    Request  = Google::Protobuf::DescriptorPool.generated_pool.lookup('micro_rb.debug.Request').msgclass
    Response = Google::Protobuf::DescriptorPool.generated_pool.lookup('micro_rb.debug.Response').msgclass
  end
end
