source 'https://rubygems.org'

gem 'rake'

gem 'bundler'
gem 'micro-rb'
<% if @encryption %>
gem 'symmetric-encryption'
<%end%>
<% if @active_record %>
gem 'activerecord'
gem <%= "'#{@engine}'" %>
<% end %>

group :test do
  gem 'minitest'
  gem 'minitest-reporters'
end
